# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-FF2_eT863I9dUSn1q3qecSlEwTwB9ka
"""

import pandas as pd

baza = {
    "Ism va Familiya": [
        "Alisher Karimov", "Madina Tursunova", "Rustam Ahmedov", "Dildora Usmonova",
        "Sardor Rakhimov", "Gulnora Tashmatova", "Azizbek Ismailov", "Malika Oripova",
        "Bekzod Shukurov", "Nargiza Khamidova"
    ],
    "Yosh": [24, 30, 22, 27, 25, 29, 23, 28, 26, 31],
    "Jinsi": ["Erkak", "Ayol", "Erkak", "Ayol", "Erkak", "Ayol", "Erkak", "Ayol", "Erkak","Ayol"
],
    "Maktab": [
        "1-sonli maktab", "12-sonli maktab", "5-sonli maktab",
        "23-sonli maktab", "15-sonli maktab", "7-sonli maktab",
        "18-sonli maktab", "9-sonli maktab",
        "21-sonli maktab", "14-sonli maktab"
    ],
    "Manzil": [
        "Yunusobod tumani, 14-uy", "Chilonzor tumani, 8-mavze", "Samarqand shahar, Amir Temur ko‘chasi",
        "Buxoro shahar, Nasaf ko‘chasi", "Nukus shahar, Mustaqillik ko‘chasi",
        "Andijon shahar, Ipak Yo‘li ko‘chasi", "Qarshi shahar, Navbahor ko‘chasi",
        "Namangan shahar, Islom Karimov ko‘chasi", "Farg‘ona shahar, Bobur ko‘chasi",
        "Urganch shahar, Al-Xorazmiy ko‘chasi"
    ],
    "Telefon raqami": [
        "+998-90-123-4567", "+998-91-234-5678", "+998-93-345-6789",
        "+998-94-456-7890", "+998-95-567-8901", "+998-97-678-9012",
        "+998-99-789-0123", "+998-88-890-1234", "+998-97-901-2345",
        "+998-93-012-3456"
    ]
}


db = pd.DataFrame(baza)
print(db)

filtered_db = db[(db['Yosh'] >= 22) & (db['Yosh'] <= 28) & (db['Jinsi'] == 'Ayol')]
print(filtr)